In [3]:
!pip3 install scikit-image --user

    100% |████████████████████████████████| 25.3MB 30kB/s eta 0:00:01
    100% |████████████████████████████████| 13.0MB 57kB/s eta 0:00:01
    100% |████████████████████████████████| 1.7MB 398kB/s ta 0:00:01
    100% |████████████████████████████████| 24.8MB 33kB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
    100% |████████████████████████████████| 4.4MB 166kB/s ta 0:00:011
    100% |████████████████████████████████| 2.0MB 376kB/s ta 0:00:01
    100% |████████████████████████████████| 706kB 602kB/s ta 0:00:01
    100% |████████████████████████████████| 17.3MB 47kB/s eta 0:00:011
    100% |████████████████████████████████| 71kB 2.3MB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
    100% |████████████████████████████████| 952kB 621k

In [5]:
import os
import keras
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten

from skimage import transform
from skimage.io import imread
from skimage.color import rgb2gray
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
"""
    Preprocess image, normalizing and resizing it

    :param frame: RGBA frame
"""    
def preprocess_image(frame):
    
    # Normalize Pixel Values
    normalized_frame = frame/255.0 - 0.5
    
    # Resize
    preprocessed_frame = transform.resize(normalized_frame, [150,150])
    
    return preprocessed_frame

In [20]:
doc_types = {}
imgs = []
img_type = []
dt = 0

# traverse root directory, and list directories as dirs and files as files
for root, dirs, files in os.walk("./data/dataset"):
    path = root.split(os.sep)
    for file in files:
        fname = file.split('.')[-1]
        if fname == 'fmt':
            f = open(root + '/' + file)
            doc_type = f.readline()[:-1]
            if doc_type not in doc_types:
                doc_types[doc_type] = dt
                dt += 1
            img_type.append(doc_types[doc_type])
            print(doc_type + " " + str(dt))
        elif fname == 'png':
            imgs.append(preprocess_image(imread(root + '/' + file)))

        

1040_1 1
1040_2 2
sch_a 3
4562_1 4
4562_2 5
1040_1 5
1040_2 5
sch_a 5
sch_b 6
sch_e_1 7
2106_2 8
4562_1 8
4562_2 8
1040_1 8
1040_2 8
sch_f_1 9
1040_1 9
1040_2 9
sch_a 9
sch_b 9
sch_c_2 10
sch_se_1 11
sch_se_2 12
4562_1 12
4562_2 12
1040_1 12
1040_2 12
sch_c_1 13
sch_c_2 13
sch_d_2 14
sch_se_2 14
2106_1 15
1040_1 15
1040_2 15
sch_b 15
sch_e_2 16
1040_1 16
1040_2 16
sch_a 16
sch_c_1 16
sch_e_1 16
1040_1 16
1040_2 16
sch_b 16
sch_e_2 16
2441 17
4562_1 17
4562_2 17
1040_1 17
1040_2 17
sch_a 17
sch_c_1 17
sch_d_1 18
sch_d_2 18
1040_1 18
1040_2 18
sch_se_2 18
1040_1 18
1040_2 18
1040_1 18
1040_2 18
sch_e_2 18
sch_se_2 18
2106_2 18
6251 19
1040_1 19
1040_2 19
sch_a 19
sch_b 19
sch_c_2 19
4562_2 19
1040_1 19
1040_2 19
sch_c_1 19
sch_e_1 19
4562_2 19
6251 19
1040_1 19
1040_2 19
sch_a 19
sch_b 19
sch_c_1 19
sch_d_1 19
sch_d_2 19
sch_f_1 19
2106_2 19
1040_1 19
1040_2 19
sch_b 19
sch_c_1 19
sch_e_1 19
sch_e_2 19
2106_1 19
1040_1 19
1040_2 19
sch_a 19
sch_d_1 19
2441 19
1040_1 19
1040_2 19
sch_a 19

sch_a 20
sch_b 20
sch_c_2 20
sch_d_1 20
4562_1 20
1040_1 20
1040_2 20
sch_c_2 20
2106_1 20
4562_2 20
1040_1 20
1040_2 20
sch_e_1 20
sch_se_2 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_e_2 20
2106_2 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_c_1 20
sch_d_2 20
sch_e_1 20
sch_se_1 20
2106_1 20
4562_1 20
1040_1 20
1040_2 20
sch_b 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
2441 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_c_1 20
sch_e_2 20
sch_f_1 20
sch_se_1 20
1040_1 20
1040_2 20
sch_a 20
sch_d_1 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
sch_f_2 20
sch_se_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_e_1 20
sch_e_2 20
1040_1 20
1040_2 20
sch_c_1 20
sch_se_2 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
sch_se_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
sch_e_1 20
1040_1 20
1040_2 20
sch_a 20
sch_d_1 20
sch_e_1 20
sch_e_2 20
sch_se_1 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_e_2 20
sch_se_2 20
2441 20
4562

1040_2 20
sch_a 20
sch_c_1 20
sch_c_2 20
sch_d_1 20
sch_d_2 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_e_2 20
4562_1 20
6251 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
sch_e_1 20
sch_se_1 20
sch_se_2 20
4562_2 20
1040_1 20
1040_2 20
sch_d_2 20
1040_1 20
1040_2 20
sch_d_2 20
sch_f_1 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_e_1 20
sch_e_2 20
1040_1 20
1040_2 20
sch_a 20
sch_c_1 20
sch_c_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_e_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
sch_e_2 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
sch_e_2 20
6251 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
1040_1 20
1040_2 20
sch_b 20
sch_e_1 20
1040_1 20
1040_2 20
sch_b 20
sch_c_2 20
sch_d_1 20
sch_e_2 20
sch_se_1 20
sch_se_2 20
4562_1 20
6251 20
1040_1 20
1040_2 20
sch_b 20
sch_e_2 20
sch_se_2 20
4562_1 20
6251 20
1040_1 20
1040_2 20
sch_a 20
sch_d_2 20
sch_e_2 20
4562_1 20
1040_1 20
1040_2 20
sch_c_1 20
1040_1 20


sch_f_2 20
6251 20
1040_1 20
1040_2 20
sch_d_1 20
sch_e_1 20
sch_e_2 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_e_1 20
sch_e_2 20
1040_1 20
1040_2 20
sch_b 20
sch_e_2 20
sch_f_2 20
6251 20
1040_1 20
1040_2 20
sch_c_1 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
2106_2 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_c_2 20
sch_e_1 20
sch_e_2 20
sch_f_2 20
2106_1 20
4562_1 20
6251 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_c_1 20
sch_d_2 20
sch_e_1 20
1040_1 20
1040_2 20
sch_b 20
sch_e_1 20
sch_se_2 20
4562_1 20
6251 20
1040_1 20
1040_2 20
sch_b 20
1040_1 20
1040_2 20
sch_a 20
4562_2 20
1040_1 20
1040_2 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
2106_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
sch_se_2 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
sch_f_2 20
2441 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
sch_se_1 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_e_1 20
2106_1 20
4562

1040_2 20
sch_a 20
sch_c_1 20
sch_d_1 20
sch_e_2 20
sch_se_1 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_e_2 20
sch_se_1 20
sch_se_2 20
1040_1 20
1040_2 20
sch_c_1 20
sch_e_2 20
1040_1 20
1040_2 20
sch_b 20
2106_2 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
2106_1 20
2106_2 20
1040_1 20
1040_2 20
6251 20
1040_1 20
1040_2 20
sch_b 20
sch_c_1 20
sch_e_1 20
sch_e_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_c_1 20
sch_e_2 20
2441 20
1040_1 20
1040_2 20
sch_b 20
sch_d_2 20
sch_se_2 20
2106_1 20
2106_2 20
4562_1 20
1040_1 20
1040_2 20
sch_b 20
sch_d_1 20
sch_d_2 20
2106_1 20
4562_1 20
1040_1 20
1040_2 20
sch_b 20
sch_e_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_c_1 20
sch_d_1 20
sch_e_2 20
2441 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_e_1 20
sch_e_2 20
sch_f_1 20
1040_1 20
1040_2 20
sch_b 20
2106_2 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_c_1 20
sch_c_2 20
sch_d_1 20
sch_d_2 20
2106_1 20
1040_1 20
1040_2 20
sch_b 20
4562_1 20
1040_1 20

1040_1 20
1040_2 20
sch_b 20
sch_d_2 20
sch_se_1 20
2441 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_se_1 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_e_1 20
sch_f_1 20
sch_se_2 20
1040_1 20
1040_2 20
sch_b 20
sch_d_1 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
sch_se_1 20
sch_se_2 20
1040_1 20
1040_2 20
sch_a 20
sch_c_1 20
sch_e_1 20
sch_se_1 20
2106_1 20
1040_1 20
1040_2 20
sch_b 20
sch_d_1 20
sch_e_1 20
sch_f_1 20
4562_2 20
6251 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_c_1 20
sch_e_1 20
sch_e_2 20
sch_se_2 20
2106_1 20
2106_2 20
2441 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
1040_1 20
1040_2 20
sch_a 20
sch_d_2 20
sch_e_1 20
sch_f_1 20
2106_2 20
2441 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
sch_se_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_e_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
4562_2 20
1

sch_e_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_d_1 20
4562_1 20
1040_1 20
1040_2 20
sch_b 20
sch_d_1 20
sch_e_1 20
sch_se_2 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_d_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_e_1 20
sch_e_2 20
1040_1 20
1040_2 20
sch_e_1 20
1040_1 20
1040_2 20
sch_b 20
sch_e_2 20
sch_f_1 20
2106_1 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_c_2 20
sch_e_2 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_c_2 20
sch_e_1 20
sch_e_2 20
sch_se_1 20
sch_se_2 20
4562_1 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
sch_c_1 20
sch_d_2 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_c_2 20
sch_d_1 20
sch_d_2 20
sch_e_1 20
sch_e_2 20
sch_se_2 20
4562_2 20
6251 20
1040_1 20
1040_2 20
sch_b 20
sch_d_2 20
2106_2 20
1040_1 20
1040_2 20
sch_a 20
sch_b 20
4562_1 20
4562_2 20
1040_1 20
1040_2 20
sch_a 20
sch_c_1 20
sch_d_2 20
sch_e_1 20
4562_2 20
1040_1 20
1040_2 20
sch_b 20
sch_c_1 20
sch_d_1 20
1040_1 20
1040_2 20
sch_c_1 20
sch_d_1 20
sch_se_2 20
1040_1 20
1040_2 20
sch_c_1 

In [7]:
print(imgs[1].shape)
print(dt)

(150, 150)
20


In [8]:
model = Sequential()
model.add(Conv2D(20, kernel_size=(7, 7), strides=(1, 1),
                 activation='relu',
                 input_shape=(150, 150, 1)))
model.add(MaxPooling2D(pool_size=(4, 4), strides=(1, 1)))
model.add(Conv2D(50, kernel_size = (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(4, 4)))
model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(dt, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01),
              metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
np_img_type = np.zeros((len(img_type), dt))

print(len(img_type))

for i in range(len(img_type)):
    np_img_type[i, img_type[i]] = 1
print(np_img_type)

5590
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
x_train = np.expand_dims(np.asarray(imgs[:2000]), axis=3)
y_train = np_img_type[:2000,:]

x_val = np.expand_dims(np.asarray(imgs[2000:4000]), axis=3)
y_val = np_img_type[2000:4000,:]

x_test = np.expand_dims(np.asarray(imgs[4000:]), axis=3)
y_test = np_img_type[4000:,:]

print(y_train.shape)

(2000, 20)


In [13]:
model.fit(x_train, y_train,
          batch_size=100,
          epochs=2,
          verbose=1,
          validation_data=(x_val, y_val))

Train on 2000 samples, validate on 2000 samples
Epoch 1/2
2000/2000 [==============================] - 377s 188ms/step - loss: 0.2850 - acc: 0.9670 - val_loss: 0.1221 - val_acc: 1.0000
Epoch 2/2
2000/2000 [==============================] - 376s 188ms/step - loss: 0.0726 - acc: 1.0000 - val_loss: 0.0409 - val_acc: 1.0000


In [17]:
#Confution Matrix and Classification Report
Y_pred = model.predict_classes(x_test)

In [15]:
print(Y_pred)

[ 2 13 11 ...  4  0  1]


In [18]:
y_pred = Y_pred
y_true = np.argmax(y_test, axis=1)
print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Confusion Matrix
[[253   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0 253   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0 134   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0  77   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0  87   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0 161   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0 101   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0  21   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0  26   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0  25   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0   0  36   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  2